//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::BlogDto> ProjectToDto(this global::System.Linq.IQueryable<global::Blog> q)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            q,
            x1 => new global::BlogDto(
                global::System.Linq.Enumerable.Count(x1.Posts, x => x.Id == x1.Posts.Count)
            )
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::BlogDto BlogMap(global::Blog blog)
    {
        var target = new global::BlogDto(MapId(blog));
        return target;
    }
}