//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(q))]
    public partial global::System.Linq.IQueryable<global::B?>? Map(global::System.Linq.IQueryable<global::A?>? q)
    {
        if (q == null)
            return default;
#nullable disable
        return global::System.Linq.Queryable.Select(
            q,
            x => new global::B()
            {
                NestedValue = x.Nested.Value,
                Values = global::System.Linq.Enumerable.ToList(
                    global::System.Linq.Enumerable.Select(
                        x.Values,
                        x1 => new global::E()
                        {
                            Value = x1.Value,
                        }
                    )
                ),
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]
    private partial global::B? Map(global::A? source)
    {
        if (source == null)
            return default;
        var target = new global::B();
        target.NestedValue = source.Nested?.Value;
        if (source.Values != null)
        {
            target.Values = MapToListOfE(source.Values);
        }
        else
        {
            target.Values = null;
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]
    private global::E? MapToE(global::D? source)
    {
        if (source == null)
            return default;
        var target = new global::E();
        target.Value = source.Value;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::System.Collections.Generic.List<global::E?> MapToListOfE(global::System.Collections.Generic.ICollection<global::D?> source)
    {
        var target = new global::System.Collections.Generic.List<global::E?>(source.Count);
        foreach (var item in source)
        {
            target.Add(MapToE(item));
        }
        return target;
    }
}
